Update README.md
naomijub/wooridb pull request #65
Opened 2021-02-17 06:32 UTC by vrmiguel

This PR focuses on improving the legibility of the README, alongside minor typo and grammar fixes.

Notes: 
* I assumed that Woori refers to a Korean word. If I'm wrong, please let me know.
* I didn't yet go over the several SELECT request descriptions but probably will later on.

2021-02-17 11:53 UTC, naomijub requested changes

2021-02-17 11:53 UTC, naomijub commented on README.md
> +`Woori` (우리) means `our` and although I developed this DB initially alone, it is in my culture to call everything that is done for our community and by our community **ours**.
I just don't want it to have the hangul version. This is a personal reason, as well as it has a similar sounding to altaic tatar language that has sounds that variates from Biz to Bwoozi (also personal, but way less known).

2021-02-17 11:54 UTC, naomijub commented
> I didn't yet go over the several SELECT request descriptions but probably will later on.
It is just one `### Select`, I should have done the examples with `####`. Will fix this soon, thanks.

2021-02-17 11:55 UTC, naomijub commented
Also, thanks on the congrats and the reviews.

2021-02-18 04:24 UTC, vrmiguel commented
I removed the hangul and added some other minor stuff

2021-02-18 05:58 UTC, naomijub commented on README.md
> +Select sll entities from `my_entity` with all the keys from each entity.
`sll`

2021-02-18 06:00 UTC, naomijub commented on README.md
> +Select sll entities from `my_entity` with all the keys from each entity.
@vrmiguel one more thing

2021-02-18 17:41 UTC, vrmiguel commented
Fixed the 'sll' typo

2021-02-18 17:48 UTC, naomijub approved these changes

2021-02-18 17:48 UTC, merged